export const quotes = [
    { id: 1, quote: "We interrupt this program to annoy you and make things generally more irritating.", open: false },
    { id: 2, quote: "He's not the Messiah—he's a very naughty boy!", open: false },
    { id: 3, quote: "Strange women lying in ponds, distributing swords, is no basis for a system of government!", open: false },
    { id: 4, quote: "The mill's closed…", open: false },
    { id: 5, quote: "But kids were different in them days…", open: false },
    { id: 6, quote: "Shut up, you American…", open: false },
    { id: 7, quote: "We use only the finest baby frogs…", open: false },
    { id: 8, quote: "My brain hurts!", open: false },
    { id: 10, quote: "There's nothing wrong with you that an expensive operation can't prolong.", open: false },
    { id: 11, quote: "This is a vegetarian restaurant…", open: false },
    { id: 12, quote: "Tonight, instead of discussing the existence or non-existence of God, they have decided to fight for it.", open: false },
    { id: 13, quote: "She's a witch! Burn her already!", open: false },
    { id: 14, quote: "It's just gone eight o'clock and time for the penguin on top of your television set to explode.", open: false },
    { id: 15, quote: "Let me tell you something, my lad…", open: false },
    { id: 16, quote: "Oh! Now we see the violence inherent in the system! Help, help, I'm being repressed!", open: false },
    { id: 17, quote: "There are a great many people in the country today, who through no fault of their own, are sane.", open: false },
    { id: 18, quote: "Let's not bicker and argue over who killed who.", open: false },
    { id: 19, quote: "Are you suggesting that coconuts migrate?", open: false },
    { id: 20, quote: "Strange Women Lyin' In Ponds Distributin' Swords Is No System For A Basis Of Government.", open: false },
    { id: 21, quote: "I Thought Your Son Was A Lady.", open: false },
    { id: 22, quote: "There Are Those Who Call Me...Tim.", open: false }
]