export const quotes = [
    { id: 1, quote: "We interrupt this program to annoy you and make things generally more irritating." },
    { id: 2, quote: "He's not the Messiah—he's a very naughty boy!" },
    { id: 3, quote: "Strange women lying in ponds, distributing swords, is no basis for a system of government!" },
    { id: 4, quote: "img" },
    { id: 5, quote: "My brain hurts!" },
    { id: 6, quote: "Tonight, instead of discussing the existence or non-existence of God, they have decided to fight for it." },
    { id: 7, quote: "She's a witch! Burn her already!" },
    { id: 8, quote: "It's just gone eight o'clock and time for the penguin on top of your television set to explode." },
    { id: 9, quote: "Oh! Now we see the violence inherent in the system! Help, help, I'm being repressed!" },
    { id: 10, quote: "Let's not bicker and argue over who killed who." },
    { id: 11, quote: "Are you suggesting that coconuts migrate?" },
    { id: 12, quote: "Strange women lying in ponds, distributing swords, is no basis for a system of government!" },
    { id: 13, quote: "I Thought Your Son Was A Lady." },
    { id: 14, quote: "We interrupt this program to annoy you and make things generally more irritating." },
    { id: 15, quote: "He's not the Messiah—he's a very naughty boy!" },
    { id: 16, quote: "My brain hurts!" },
    { id: 17, quote: "Tonight, instead of discussing the existence or non-existence of God, they have decided to fight for it." },
    { id: 18, quote: "She's a witch! Burn her already!" },
    { id: 19, quote: "It's just gone eight o'clock and time for the penguin on top of your television set to explode." },
    { id: 20, quote: "Oh! Now we see the violence inherent in the system! Help, help, I'm being repressed!" },
    { id: 21, quote: "Let's not bicker and argue over who killed who." },
    { id: 22, quote: "Are you suggesting that coconuts migrate?" },
    { id: 23, quote: "I Thought Your Son Was A Lady." },
    { id: 24, quote: "img" }
]